# Generated by Django 5.2.6 on 2025-10-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full detailed description with usage, dosage, warnings, etc.'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 10ml', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (recommended size: 800x800px)', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, help_text='e.g., 30 tablets, 100ml bottle', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Short description shown in product grid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (optional, use image upload instead)', null=True),
        ),
    ]
