# Generated by Django 5.2.6 on 2026-04-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price',
            field=models.BooleanField(default=False, help_text='Display price publicly on the storefront. When off, customers see an inquiry link instead.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['show_price'], name='api_product_show_pr_ebef13_idx'),
        ),
    ]
