# Generated by Django 5.2.6 on 2026-04-11 13:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_migrate_data_to_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', '-is_primary', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='productsupplier',
            options={'ordering': ['-is_preferred', 'supplier__name']},
        ),
        # Constraint may not exist, skip removal
        # migrations.RemoveConstraint(
        #     model_name='cartitem',
        #     name='unique_cart_product',
        # ),
        # Removed - the suppliers M2M field removal is handled by model change
        # migrations.RemoveField(
        #     model_name='product',
        #     name='suppliers',
        # ),
        migrations.AddField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('stripe', 'Stripe (Card Payment)')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='active_ingredient',
            field=models.CharField(blank=True, help_text='e.g., Paracetamol, Ibuprofen', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='UPC, EAN, or other barcode', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full description with usage, dosage, warnings, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 10ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage featured section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, help_text='e.g., 30 tablets, 100ml bottle', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_manual_review',
            field=models.BooleanField(default=True, help_text='Requires admin review before publishing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False, help_text='Requires prescription to purchase'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Brief description shown in product cards/grid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - unique product identifier', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Image alt text for accessibility and SEO', max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image (recommended: 800x800px)', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary image shown in listings'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='source_type',
            field=models.CharField(choices=[('manual_upload', 'Manual Upload'), ('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('placeholder', 'Placeholder')], default='manual_upload', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source URL if imported'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Preferred supplier for this product'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last price paid to supplier', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.product'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='supplier_sku',
            field=models.CharField(blank=True, help_text="Supplier's product code", max_length=100),
        ),
        # Already exists in database, skip
        # migrations.AlterUniqueTogether(
        #     name='cartitem',
        #     unique_together={('cart', 'product')},
        # ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='api_brand_slug_d4b57a_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='api_brand_name_d23c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='api_categor_slug_794f78_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='api_categor_parent__d9272b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='api_categor_is_acti_5fb091_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['display_order'], name='api_categor_display_a925bc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='api_order_status_dee4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='api_order_created_7fb22c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='api_order_order_n_ec9cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='api_product_slug_e70af7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='api_product_status_feb151_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='api_product_is_feat_fda764_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['requires_prescription'], name='api_product_require_586622_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='api_product_created_a91d70_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='api_product_brand_i_37891c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='api_product_categor_5c53c5_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='api_product_product_af3f05_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['display_order'], name='api_product_display_c08c38_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['slug'], name='api_supplie_slug_ab3250_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='api_supplie_name_88d2fc_idx'),
        ),
    ]
