# Generated by Django 5.2.6 on 2026-09-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retain_orders_after_user_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identity_notes',
            field=models.JSONField(blank=True, default=dict, db_default={}),
        ),
        migrations.AddField(
            model_name='product',
            name='identity_review_state',
            field=models.CharField(choices=[('verified', 'Verified'), ('provisional', 'Needs identity review')], db_index=True, default='verified', db_default='verified', max_length=20),
        ),
    ]
