# Generated by Django 5.2.6 on 2026-04-11 13:38
# Fixed to handle cases where constraint may not exist

from django.db import migrations


def fix_cartitem_constraint(apps, schema_editor):
    """Ensure cart-product unique constraint exists."""
    # This is a no-op since AlterUniqueTogether in earlier migrations
    # should have handled this, but we keep it for safety
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_finalize_v2_schema'),
    ]

    operations = [
        # Just run a no-op - constraints are handled in earlier migrations
        migrations.RunPython(fix_cartitem_constraint, migrations.RunPython.noop),
    ]
