# Generated by Django 5.2.6 on 2026-09-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_identity_notes_product_identity_review_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_variants', to='api.product'),
        ),
    ]
