# Generated by Django 5.2.6 on 2026-04-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_finalize_v2_schema'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_product',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
