release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: gunicorn pharmacy_api.wsgi --timeout ${GUNICORN_TIMEOUT:-120} --workers ${WEB_CONCURRENCY:-2} --threads ${GUNICORN_THREADS:-2} --log-file -
