# Generated by Django 5.2.6 on 2026-05-20 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_add_show_price_to_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.TextField(blank=True)),
                ('trn', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['normalized_name'], name='quotations__normali_3e5112_idx'), models.Index(fields=['is_active'], name='quotations__is_acti_34190f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='quotations.company')),
            ],
            options={
                'ordering': ['company__name', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('original_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='quotations.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='quotations.companycontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('match_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='unresolved', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.inquiry')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('sent', 'Sent'), ('revised', 'Revised'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='quotations.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations.companycontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_quotations', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotations.inquiry')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('finalized', 'Finalized'), ('revised', 'Revised'), ('pdf_downloaded', 'PDF Downloaded')], max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='quotations.company')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('internal_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('brand_text', models.CharField(blank=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('pack_size', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='api.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_snapshot', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('match_status', models.CharField(choices=[('unresolved', 'Unresolved'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='unresolved', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='quotations.inquiryline')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.quotation')),
                ('quote_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='quotations.quoteitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='matched_quote_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_lines', to='quotations.quoteitem'),
        ),
        migrations.CreateModel(
            name='CompanyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quoted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='quotations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_history', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history_entries', to='quotations.quotation')),
                ('quotation_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='price_history_entry', to='quotations.quotationline')),
                ('quote_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_price_history', to='quotations.quoteitem')),
            ],
            options={
                'ordering': ['-quoted_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'is_primary'], name='quotations__company_3a6b64_idx'),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['is_active'], name='quotations__is_acti_4c11f8_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['company', 'status'], name='quotations__company_3b03ea_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['received_at'], name='quotations__receive_502ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['created_by'], name='quotations__created_e7b383_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotations__quotati_d2f33a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'status'], name='quotations__company_a4be29_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='quotations__status_2435f4_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_by'], name='quotations__created_522051_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['parent', 'version'], name='quotations__parent__9a59e7_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationauditlog',
            index=models.Index(fields=['action', 'created_at'], name='quotations__action_04f1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationauditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='quotations__target__5cc585_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationauditlog',
            index=models.Index(fields=['company', 'created_at'], name='quotations__company_91d75c_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationauditlog',
            index=models.Index(fields=['quotation', 'created_at'], name='quotations__quotati_e7f6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['normalized_name'], name='quotations__normali_02359c_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['internal_code'], name='quotations__interna_7abf0a_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['is_active'], name='quotations__is_acti_d96535_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['product'], name='quotations__product_624d70_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['quotation', 'sort_order'], name='quotations__quotati_0d72a6_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['quote_item'], name='quotations__quote_i_51a5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['match_status'], name='quotations__match_s_f63d05_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryline',
            index=models.Index(fields=['inquiry', 'sort_order'], name='quotations__inquiry_a39152_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryline',
            index=models.Index(fields=['match_status'], name='quotations__match_s_2826c1_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryline',
            index=models.Index(fields=['matched_quote_item'], name='quotations__matched_3eacf3_idx'),
        ),
        migrations.AddIndex(
            model_name='companypricehistory',
            index=models.Index(fields=['company', 'quote_item', 'quoted_at'], name='quotations__company_e71905_idx'),
        ),
        migrations.AddIndex(
            model_name='companypricehistory',
            index=models.Index(fields=['quotation'], name='quotations__quotati_2b839c_idx'),
        ),
    ]
