# Generated by Django 5.2.6 on 2026-05-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='parse_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parse_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('pasted_text', 'Pasted Text'), ('excel', 'Excel'), ('pdf', 'PDF')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='parse_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='parse_status',
            field=models.CharField(choices=[('manual', 'Manual'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('unparsed', 'Unparsed')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='raw_line',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='quotationauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('finalized', 'Finalized'), ('revised', 'Revised'), ('pdf_downloaded', 'PDF Downloaded'), ('imported', 'Imported')], max_length=50),
        ),
    ]
