# Generated by Django 5.2.6 on 2026-05-21 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_inquiry_parse_meta_inquiry_parse_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Al Ameen Pharmacy', max_length=255)),
                ('company_name_ar', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True, default='Dubai, United Arab Emirates')),
                ('phone', models.CharField(blank=True, default='+971 50 545 6388', max_length=80)),
                ('email', models.EmailField(blank=True, default='alameenpharmacyllc@gmail.com', max_length=254)),
                ('trn', models.CharField(blank=True, max_length=80)),
                ('license_number', models.CharField(blank=True, max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='quotations/logos/')),
                ('footer_note', models.TextField(blank=True)),
                ('default_terms', models.TextField(blank=True, default='Prices are subject to stock availability and final confirmation. This quotation is confidential and intended for the named customer only.')),
                ('payment_terms', models.TextField(blank=True, default='Payment terms to be confirmed with the customer.')),
                ('validity_days', models.PositiveIntegerField(default=14)),
                ('prepared_by_default', models.CharField(blank=True, max_length=255)),
                ('signature_label', models.CharField(blank=True, default='Signature', max_length=120)),
                ('stamp_label', models.CharField(blank=True, default='Stamp', max_length=120)),
                ('pdf_template_style', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('compact', 'Compact')], default='classic', max_length=30)),
                ('primary_color', models.CharField(default='#0F766E', max_length=7)),
                ('accent_color', models.CharField(default='#ECFDF5', max_length=7)),
                ('show_arabic_name', models.BooleanField(default=True)),
                ('show_trn', models.BooleanField(default=True)),
                ('show_license_number', models.BooleanField(default=True)),
                ('show_signature_area', models.BooleanField(default=True)),
                ('show_stamp_area', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation Settings',
                'verbose_name_plural': 'Quotation Settings',
            },
        ),
    ]
