# Generated by Django 5.2.6 on 2026-05-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsettings',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/signatures/'),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/stamps/'),
        ),
    ]
