# Generated by Django 5.2.6 on 2026-05-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotationsettings_signature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsettings',
            name='logo_layout',
            field=models.CharField(choices=[('full_logo_only', 'Full logo only'), ('logo_plus_company_text', 'Logo plus company text'), ('icon_left_company_text', 'Icon left, company text'), ('no_logo', 'No logo')], default='full_logo_only', max_length=40),
        ),
    ]
