# Generated by Django 5.2.6 on 2026-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quotationsettings_logo_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='source_file_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
