# Generated by Django 5.2.6 on 2026-05-22 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_inquiry_source_file_ref_inquiry_source_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPriceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_company_name', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF')], default='pdf', max_length=30)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_mime_type', models.CharField(blank=True, max_length=120)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_file_ref', models.CharField(blank=True, max_length=500)),
                ('source_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_method', models.CharField(blank=True, max_length=80)),
                ('parse_meta', models.JSONField(blank=True, default=dict)),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('document_date', models.DateField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('reviewed', 'Reviewed'), ('committed', 'Committed'), ('cancelled', 'Cancelled')], default='parsed', max_length=30)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPriceImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_line', models.TextField(blank=True)),
                ('item_name', models.CharField(max_length=255)),
                ('normalized_item_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=30)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('ready', 'Ready'), ('skipped', 'Skipped'), ('duplicate', 'Duplicate'), ('committed', 'Committed')], default='needs_review', max_length=30)),
                ('duplicate_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_historical_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['is_historical_import'], name='quotations__is_hist_93e168_idx'),
        ),
        migrations.AddField(
            model_name='historicalpriceimport',
            name='committed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_historical_price_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpriceimport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_price_imports', to='quotations.company'),
        ),
        migrations.AddField(
            model_name='historicalpriceimport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_historical_price_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpriceimport',
            name='created_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_price_import', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='historicalpriceimportline',
            name='historical_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.historicalpriceimport'),
        ),
        migrations.AddField(
            model_name='historicalpriceimportline',
            name='quote_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_import_lines', to='quotations.quoteitem'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimport',
            index=models.Index(fields=['source_sha256'], name='quotations__source__86ba50_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimport',
            index=models.Index(fields=['company', 'document_date'], name='quotations__company_bde3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimport',
            index=models.Index(fields=['document_number'], name='quotations__documen_0bd180_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimport',
            index=models.Index(fields=['status'], name='quotations__status_92ccea_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimportline',
            index=models.Index(fields=['historical_import', 'sort_order'], name='quotations__histori_c6242e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimportline',
            index=models.Index(fields=['quote_item'], name='quotations__quote_i_20129c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimportline',
            index=models.Index(fields=['status'], name='quotations__status_6859ea_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimportline',
            index=models.Index(fields=['normalized_item_name'], name='quotations__normali_baf7b5_idx'),
        ),
    ]
