# Generated by Django 5.2.6 on 2026-05-24 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_show_price_to_product'),
        ('quotations', '0007_historicalpriceimport_historicalpriceimportline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company__name', 'alias'],
            },
        ),
        migrations.AddField(
            model_name='companypricehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_price_history', to='api.product'),
        ),
        migrations.AddField(
            model_name='historicalpriceimportline',
            name='match_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpriceimportline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_import_lines', to='api.product'),
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='match_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_inquiry_lines', to='api.product'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='match_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='api.product'),
        ),
        migrations.AlterField(
            model_name='companypricehistory',
            name='quote_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_price_history', to='quotations.quoteitem'),
        ),
        migrations.AddIndex(
            model_name='companypricehistory',
            index=models.Index(fields=['company', 'product', 'quoted_at'], name='quotations__company_97d338_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimportline',
            index=models.Index(fields=['product'], name='quotations__product_81ed83_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryline',
            index=models.Index(fields=['matched_product'], name='quotations__matched_fe5fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['product'], name='quotations__product_8f5552_idx'),
        ),
        migrations.AddField(
            model_name='productalias',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Blank means a global alias. Company-specific aliases override global aliases.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_aliases', to='quotations.company'),
        ),
        migrations.AddField(
            model_name='productalias',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_aliases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productalias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_aliases', to='api.product'),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['company', 'normalized_alias'], name='quotations__company_4b134c_idx'),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['product'], name='quotations__product_b2ff47_idx'),
        ),
        migrations.AddIndex(
            model_name='productalias',
            index=models.Index(fields=['is_active'], name='quotations__is_acti_c69ba5_idx'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'normalized_alias'), name='uniq_company_product_alias'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('normalized_alias',), name='uniq_global_product_alias'),
        ),
    ]
