# Generated by Django 5.2.6 on 2026-05-26 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_productalias_companypricehistory_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsettings',
            name='ai_auto_cleanup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='ai_parsing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationsettings',
            name='ai_pdf_vision_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AIParseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('context_hash', models.CharField(db_index=True, max_length=64)),
                ('mode', models.CharField(choices=[('text', 'Text cleanup'), ('vision', 'Vision cleanup')], max_length=20)),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=120)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['source_sha256', 'mode'], name='quotations__source__012aad_idx'), models.Index(fields=['provider', 'model'], name='quotations__provide_c86211_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('text', 'Text cleanup'), ('vision', 'Vision cleanup')], max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('context_hash', models.CharField(blank=True, max_length=64)),
                ('cache_hit', models.BooleanField(default=False)),
                ('text_length', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_ai_parse_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'model', 'mode'], name='quotations__provide_bf952f_idx'), models.Index(fields=['success', 'created_at'], name='quotations__success_8d9e0f_idx')],
            },
        ),
    ]
