# Generated by Django 5.2.6 on 2026-06-02 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_show_price_to_product'),
        ('quotations', '0009_quotationsettings_ai_auto_cleanup_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('committed', 'Committed'), ('failed', 'Failed')], default='created', max_length=30)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_historical_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalImportAISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('company', 'Company'), ('line', 'Line')], default='line', max_length=20)),
                ('action', models.CharField(choices=[('match_existing_product', 'Match Existing Product'), ('create_company_alias', 'Create Company Alias'), ('create_new_product', 'Create New Product'), ('needs_manual_review', 'Needs Manual Review'), ('skip', 'Skip'), ('match_existing_company', 'Match Existing Company'), ('create_new_company', 'Create New Company')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('conflict', 'Conflict'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('alias_text', models.CharField(blank=True, max_length=255)),
                ('proposed_company_name', models.CharField(blank=True, max_length=255)),
                ('proposed_product_name', models.CharField(blank=True, max_length=255)),
                ('proposed_unit', models.CharField(blank=True, max_length=80)),
                ('proposed_pack_size', models.CharField(blank=True, max_length=120)),
                ('proposed_dosage', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('candidate_companies', models.JSONField(blank=True, default=list)),
                ('candidate_products', models.JSONField(blank=True, default=list)),
                ('raw_ai_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_historical_ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_historical_ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('historical_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='quotations.historicalpriceimport')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='quotations.historicalpriceimportline')),
                ('suggested_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_ai_company_suggestions', to='quotations.company')),
                ('suggested_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_ai_product_suggestions', to='api.product')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='quotations.historicalimportbatch')),
            ],
            options={
                'ordering': ['historical_import', 'line__sort_order', 'suggestion_type', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalpriceimport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='quotations.historicalimportbatch'),
        ),
        migrations.AddIndex(
            model_name='historicalpriceimport',
            index=models.Index(fields=['batch', 'status'], name='quotations__batch_i_a647e0_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportbatch',
            index=models.Index(fields=['status'], name='quotations__status_d14667_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportbatch',
            index=models.Index(fields=['created_by'], name='quotations__created_bbd4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportaisuggestion',
            index=models.Index(fields=['batch', 'status'], name='quotations__batch_i_5bf3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportaisuggestion',
            index=models.Index(fields=['historical_import', 'status'], name='quotations__histori_f8a18a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportaisuggestion',
            index=models.Index(fields=['line', 'status'], name='quotations__line_id_77e430_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportaisuggestion',
            index=models.Index(fields=['action'], name='quotations__action_28a175_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalimportaisuggestion',
            index=models.Index(fields=['confidence'], name='quotations__confide_c22969_idx'),
        ),
    ]
