# Generated by Django 5.2.6 on 2026-06-04 07:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_historicalimportbatch_historicalimportaisuggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inquiryline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
