# Generated by Django 5.2.6 on 2026-06-04 11:41

from django.db import migrations, models


def update_existing_default_terms(apps, schema_editor):
    QuotationSettings = apps.get_model("quotations", "QuotationSettings")
    old_payment_text = "Payment terms to be confirmed with the customer."
    for settings_obj in QuotationSettings.objects.all():
        changed_fields = []
        if settings_obj.validity_days == 14:
            settings_obj.validity_days = 30
            changed_fields.append("validity_days")
        if (settings_obj.payment_terms or "").strip() in {"", old_payment_text}:
            settings_obj.payment_terms = "Credit 30 days"
            changed_fields.append("payment_terms")
        if changed_fields:
            settings_obj.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_inquiryline_unit_price_inquiryline_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(choices=[('credit_30_days', 'Credit 30 days'), ('credit_60_days', 'Credit 60 days'), ('advance_100', '100% advance'), ('pdc_30_days', 'PDC 30 days'), ('cash', 'Cash'), ('pdc_60_days', 'PDC 60 days')], default='credit_30_days', max_length=40),
        ),
        migrations.AlterField(
            model_name='quotationsettings',
            name='payment_terms',
            field=models.TextField(blank=True, default='Credit 30 days'),
        ),
        migrations.AlterField(
            model_name='quotationsettings',
            name='validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.RunPython(update_existing_default_terms, migrations.RunPython.noop),
    ]
