# Generated by Django 5.2.6 on 2026-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_quotation_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(choices=[('credit_30_days', 'Credit 30 days'), ('credit_60_days', 'Credit 60 days'), ('advance_100', '100% advance'), ('pdc_30_days', 'PDC 30 days'), ('cash', 'Cash'), ('pdc_60_days', 'PDC 60 days'), ('as_per_agreement', 'As per agreement')], default='credit_30_days', max_length=40),
        ),
    ]
