# Generated by Django 5.2.6 on 2026-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_userquotationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
