# Generated by Django 5.2.6 on 2026-06-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_show_price_to_product'),
        ('quotations', '0015_companycontact_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='include_product_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='api.productimage'),
        ),
    ]
