# Generated by Django 5.2.6 on 2026-06-15 13:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retain_orders_after_user_delete'),
        ('quotations', '0017_default_payment_terms_as_per_agreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationOutcomePOImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('pasted_text', 'Pasted text'), ('file', 'File')], max_length=30)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_file_ref', models.CharField(blank=True, max_length=500)),
                ('parse_method', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('failed', 'Failed')], default='parsed', max_length=30)),
                ('parsed_rows', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('unmatched_po_rows', models.JSONField(blank=True, default=list)),
                ('missing_quote_line_ids', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='follow_up_contact_method',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('visit', 'Visit'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='follow_up_status',
            field=models.CharField(choices=[('open', 'Open'), ('due', 'Due'), ('overdue', 'Overdue'), ('done', 'Done'), ('not_required', 'Not required')], db_index=True, default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='next_follow_up_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_quotation_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotation_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('partial', 'Partial'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='outcome_status_is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='accepted_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='accepted_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='accepted_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='accepted_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='lost_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='lost_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='outcome_reason',
            field=models.CharField(blank=True, choices=[('price_too_high', 'Price too high'), ('not_available', 'Not available'), ('customer_no_longer_required', 'Customer no longer required'), ('competitor_selected', 'Competitor selected'), ('alternate_brand_selected', 'Alternate brand selected'), ('quantity_changed', 'Quantity changed'), ('delivery_time_issue', 'Delivery time issue'), ('customer_cancelled', 'Customer cancelled'), ('no_response', 'No response'), ('unknown', 'Unknown')], max_length=40),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='outcome_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('unavailable_missing', 'Unavailable / missing'), ('substituted', 'Substituted'), ('quantity_changed', 'Quantity changed')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='quoted_gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quotationauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('finalized', 'Finalized'), ('revised', 'Revised'), ('pdf_downloaded', 'PDF Downloaded'), ('imported', 'Imported'), ('outcome_updated', 'Outcome Updated'), ('followup_updated', 'Follow-up Updated')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['outcome_status', 'created_at'], name='quotations__outcome_210b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['follow_up_status', 'next_follow_up_date'], name='quotations__follow__e71d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['outcome_status'], name='quotations__outcome_d8db8a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationline',
            index=models.Index(fields=['outcome_reason'], name='quotations__outcome_fe0c00_idx'),
        ),
        migrations.AddField(
            model_name='quotationoutcomepoimport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outcome_po_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationoutcomepoimport',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_po_imports', to='quotations.quotation'),
        ),
        migrations.AddIndex(
            model_name='quotationoutcomepoimport',
            index=models.Index(fields=['quotation', 'created_at'], name='quotations__quotati_f27817_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationoutcomepoimport',
            index=models.Index(fields=['status', 'created_at'], name='quotations__status_155653_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationoutcomepoimport',
            index=models.Index(fields=['source_sha256'], name='quotations__source__3d40ba_idx'),
        ),
    ]
