# Generated by Django 5.2.6 on 2026-06-17 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0018_quotationoutcomepoimport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('finalized', 'Finalized'), ('revised', 'Revised'), ('pdf_downloaded', 'PDF Downloaded'), ('imported', 'Imported'), ('lpo_uploaded', 'LPO Uploaded'), ('proforma_downloaded', 'Proforma Downloaded'), ('outcome_updated', 'Outcome Updated'), ('followup_updated', 'Follow-up Updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuotationLPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('file', 'File'), ('pasted_text', 'Pasted text')], default='file', max_length=30)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_file_ref', models.CharField(blank=True, max_length=500)),
                ('source_file_size', models.PositiveIntegerField(default=0)),
                ('parse_method', models.CharField(blank=True, max_length=100)),
                ('lpo_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('lpo_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('parsed', 'Parsed'), ('needs_review', 'Needs review'), ('confirmed', 'Confirmed')], db_index=True, default='received', max_length=30)),
                ('parsed_meta', models.JSONField(blank=True, default=dict)),
                ('parsed_rows', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpos', to='quotations.quotation')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_quotation_lpos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['quotation', 'received_at'], name='quotations__quotati_24927b_idx'), models.Index(fields=['quotation', 'status'], name='quotations__quotati_5a08a2_idx'), models.Index(fields=['source_sha256'], name='quotations__source__f0da89_idx'), models.Index(fields=['lpo_date'], name='quotations__lpo_dat_a9964e_idx')],
            },
        ),
    ]
