# Generated by Django 5.2.6 on 2026-06-17 15:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retain_orders_after_user_delete'),
        ('quotations', '0019_alter_quotationauditlog_action_quotationlpo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('proforma_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('lpo_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('lpo_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('file', 'File'), ('pasted_text', 'Pasted text')], max_length=30)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_file_ref', models.CharField(blank=True, max_length=500)),
                ('source_file_size', models.PositiveIntegerField(default=0)),
                ('parse_method', models.CharField(blank=True, max_length=100)),
                ('parsed_meta', models.JSONField(blank=True, default=dict)),
                ('parsed_rows', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='quotations.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoices', to='quotations.companycontact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proforma_invoices', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_proforma_invoices', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_proformas', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_lines', to='api.product')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.proformainvoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['proforma_number'], name='quotations__proform_481580_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['company', 'status'], name='quotations__company_6c8a23_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['status', 'created_at'], name='quotations__status_01794b_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['lpo_number'], name='quotations__lpo_num_a37feb_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['lpo_date'], name='quotations__lpo_dat_46dc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoice',
            index=models.Index(fields=['source_sha256'], name='quotations__source__5ce8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoiceline',
            index=models.Index(fields=['proforma', 'sort_order'], name='quotations__proform_76c3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='proformainvoiceline',
            index=models.Index(fields=['product'], name='quotations__product_d179f0_idx'),
        ),
    ]
