# Generated by Django 5.2.6 on 2026-06-22 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_retain_orders_after_user_delete'),
        ('quotations', '0020_proformainvoice_proformainvoiceline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractIntelligenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_company_name', models.CharField(max_length=255)),
                ('gmail_query', models.TextField(blank=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('max_messages', models.PositiveIntegerField(default=100)),
                ('include_attachments', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('discovering', 'Discovering'), ('ready', 'Ready'), ('analyzing', 'Analyzing'), ('review', 'Review'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('ai_status', models.CharField(blank=True, max_length=80)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_intelligence_runs', to='quotations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_intelligence_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractIntelligenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=500)),
                ('recipients', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('classification', models.CharField(choices=[('inquiry', 'Inquiry / RFQ'), ('quotation', 'Quotation sent'), ('lpo', 'LPO / order'), ('followup', 'Follow-up'), ('irrelevant', 'Irrelevant'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(default='fetched', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='quotations.contractintelligencerun')),
            ],
            options={
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractIntelligenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_item_name', models.CharField(max_length=500)),
                ('normalized_item_name', models.CharField(db_index=True, max_length=500)),
                ('suggested_item_name', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('contact_text', models.CharField(blank=True, max_length=255)),
                ('source_text', models.TextField(blank=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_page', models.CharField(blank=True, max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('ai_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='suggested', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_intelligence_items', to='api.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.contractintelligencerun')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='quotations.contractintelligencesource')),
            ],
            options={
                'ordering': ['normalized_item_name', '-requested_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailOAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_subject', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='connected', max_length=30)),
                ('last_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_gmail_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contractintelligencerun',
            index=models.Index(fields=['company', 'created_at'], name='quotations__company_36a9be_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligencerun',
            index=models.Index(fields=['status', 'created_at'], name='quotations__status_6be73c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligencerun',
            index=models.Index(fields=['created_by', 'created_at'], name='quotations__created_b8f672_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligencesource',
            index=models.Index(fields=['run', 'classification'], name='quotations__run_id_5da76c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligencesource',
            index=models.Index(fields=['gmail_message_id'], name='quotations__gmail_m_4cae86_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligencesource',
            index=models.Index(fields=['sent_at'], name='quotations__sent_at_c719b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractintelligencesource',
            constraint=models.UniqueConstraint(condition=models.Q(('gmail_message_id__gt', '')), fields=('run', 'gmail_message_id'), name='uniq_contract_run_gmail_message'),
        ),
        migrations.AddIndex(
            model_name='contractintelligenceitem',
            index=models.Index(fields=['run', 'status'], name='quotations__run_id_ffff3e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligenceitem',
            index=models.Index(fields=['normalized_item_name'], name='quotations__normali_e0a564_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligenceitem',
            index=models.Index(fields=['requested_date'], name='quotations__request_d95c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractintelligenceitem',
            index=models.Index(fields=['product'], name='quotations__product_b3a5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailoauthconnection',
            index=models.Index(fields=['status'], name='quotations__status_9c11ae_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailoauthconnection',
            index=models.Index(fields=['email'], name='quotations__email_61d516_idx'),
        ),
    ]
