# Generated by Django 5.2.6 on 2026-06-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_contractintelligencerun_contractintelligencesource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractintelligencerun',
            name='discovery_batch_size',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='contractintelligencerun',
            name='discovery_exhausted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractintelligencerun',
            name='discovery_page_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractintelligencerun',
            name='discovery_result_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractintelligencerun',
            name='sender_domain_hint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
