# Generated by Django 5.2.6 on 2026-07-01 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_contractintelligencerun_discovery_batch_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationoutcomepoimport',
            name='source_type',
            field=models.CharField(choices=[('pasted_text', 'Pasted text'), ('file', 'File'), ('gmail', 'Gmail evidence')], max_length=30),
        ),
        migrations.CreateModel(
            name='QuotationPOEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sender', models.CharField(blank=True, max_length=500)),
                ('recipients', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('source_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('matching_reason', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('parsed', 'Parsed'), ('not_relevant', 'Not relevant'), ('failed', 'Failed')], default='candidate', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quote_po_evidence', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_evidence', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-confidence', '-sent_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotationoutcomepoimport',
            name='gmail_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_imports', to='quotations.quotationpoevidence'),
        ),
        migrations.AddIndex(
            model_name='quotationpoevidence',
            index=models.Index(fields=['quotation', 'status'], name='quotations__quotati_7e2281_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationpoevidence',
            index=models.Index(fields=['quotation', 'confidence'], name='quotations__quotati_3e97ec_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationpoevidence',
            index=models.Index(fields=['sent_at'], name='quotations__sent_at_71296c_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationpoevidence',
            index=models.Index(fields=['source_sha256'], name='quotations__source__c021e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotationpoevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('gmail_message_id', ''), _negated=True), fields=('quotation', 'gmail_message_id'), name='unique_quote_po_evidence_message'),
        ),
    ]
