# Generated by Django 5.2.6 on 2026-07-15 00:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_po_evidence_source_keys(apps, schema_editor):
    evidence_model = apps.get_model('quotations', 'QuotationPOEvidence')
    for evidence in evidence_model.objects.only(
        'id', 'source_sha256', 'selected_attachment_id', 'gmail_message_id'
    ).iterator(chunk_size=500):
        source_hash = str(evidence.source_sha256 or '').strip().lower()
        attachment_id = str(evidence.selected_attachment_id or '').strip()
        message_id = str(evidence.gmail_message_id or '').strip()
        if source_hash:
            source_key = f'sha256:{source_hash}'[:255]
        elif attachment_id:
            source_key = f'attachment:{attachment_id}'[:255]
        elif message_id:
            source_key = f'message:{message_id}'[:255]
        else:
            source_key = ''
        evidence_model.objects.filter(pk=evidence.pk).update(source_key=source_key)


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0027_alter_quotationpoevidence_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxPOAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('earliest_quote_at', models.DateTimeField()),
                ('mailbox_cutoff_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gmail_query', models.TextField()),
                ('page_token', models.TextField(blank=True)),
                ('exhausted', models.BooleanField(db_index=True, default=False)),
                ('result_size_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('pages_scanned', models.PositiveIntegerField(default=0)),
                ('messages_scanned', models.PositiveIntegerField(default=0)),
                ('messages_created', models.PositiveIntegerField(default=0)),
                ('relevant_messages', models.PositiveIntegerField(default=0)),
                ('incomplete_messages', models.PositiveIntegerField(default=0)),
                ('attachment_candidates', models.PositiveIntegerField(default=0)),
                ('attachment_bytes_fetched', models.PositiveBigIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('scan_lease_token', models.CharField(blank=True, max_length=64)),
                ('scan_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_page_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_audit_runs', to='quotations.gmailoauthconnection')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_mailbox_po_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailboxPOMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('mailbox_email', models.EmailField(blank=True, max_length=254)),
                ('label_ids', models.JSONField(blank=True, default=list)),
                ('full_headers', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=500)),
                ('recipients', models.TextField(blank=True)),
                ('cc', models.TextField(blank=True)),
                ('reply_to', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('newest_body_text', models.TextField(blank=True)),
                ('attachment_manifest', models.JSONField(blank=True, default=list)),
                ('classification', models.CharField(choices=[('purchase_order', 'Purchase order'), ('possible_po', 'Possible purchase order'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('is_relevant', models.BooleanField(db_index=True, default=False)),
                ('auto_link_eligible', models.BooleanField(default=True)),
                ('relevance_reason', models.TextField(blank=True)),
                ('extracted_po_references', models.JSONField(blank=True, default=list)),
                ('audit_error', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('full_message_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('attachments_audited_at', models.DateTimeField(blank=True, null=True)),
                ('last_audited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_messages', to='quotations.mailboxpoauditrun')),
                ('gmail_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_mailbox_messages', to='quotations.gmailoauthconnection')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_messages', to='quotations.mailboxpoauditrun')),
            ],
            options={
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailboxPOMatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_version', models.CharField(default='mailbox_match_v1', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_runs', to='quotations.mailboxpoauditrun')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_mailbox_po_match_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailboxPOAuditRunMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_memberships', to='quotations.mailboxpoauditrun')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_memberships', to='quotations.mailboxpomessage')),
            ],
            options={
                'ordering': ['audit_run_id', 'message_id'],
            },
        ),
        migrations.CreateModel(
            name='MailboxPOAuditFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('page_token', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('retrying', 'Retrying'), ('tombstoned', 'Tombstoned'), ('resolved', 'Resolved')], db_index=True, default='retrying', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('first_failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_failures', to='quotations.mailboxpoauditrun')),
            ],
            options={
                'ordering': ['audit_run_id', 'gmail_message_id'],
            },
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='mailbox_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_evidence', to='quotations.mailboxpomessage'),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='mailbox_match_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='quotations.mailboxpomatchrun'),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='match_signals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='selected_attachment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='selected_attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='quote_reference_present',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='quotationpoevidence',
            name='matched_quote_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='mailboxpoauditrun',
            index=models.Index(fields=['gmail_connection', 'status'], name='quotations__gmail_c_5b98cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxpoauditrun',
            index=models.Index(fields=['exhausted', 'created_at'], name='quotations__exhaust_e6ab25_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxpomessage',
            index=models.Index(fields=['gmail_connection', 'sent_at'], name='quotations__gmail_c_e12007_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxpomessage',
            index=models.Index(fields=['gmail_connection', 'is_relevant'], name='quotations__gmail_c_1b6975_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxpomessage',
            index=models.Index(fields=['classification', 'sent_at'], name='quotations__classif_f50e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxpomatchrun',
            index=models.Index(fields=['audit_run', 'status'], name='quotations__audit_r_62ae93_idx'),
        ),
        migrations.AddConstraint(
            model_name='mailboxpomessage',
            constraint=models.UniqueConstraint(fields=('gmail_connection', 'gmail_message_id'), name='unique_mailbox_po_message'),
        ),
        migrations.AddConstraint(
            model_name='mailboxpoauditrunmessage',
            constraint=models.UniqueConstraint(fields=('audit_run', 'message'), name='unique_mailbox_po_run_message'),
        ),
        migrations.AddConstraint(
            model_name='mailboxpoauditfailure',
            constraint=models.UniqueConstraint(fields=('audit_run', 'gmail_message_id'), name='unique_mailbox_po_audit_failure'),
        ),
        migrations.RemoveConstraint(
            model_name='quotationpoevidence',
            name='unique_quote_po_evidence_message',
        ),
        migrations.RunPython(populate_po_evidence_source_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='quotationpoevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('gmail_connection__isnull', False), models.Q(('gmail_message_id', ''), _negated=True), models.Q(('source_key', ''), _negated=True)), fields=('quotation', 'gmail_connection', 'gmail_message_id', 'source_key'), name='unique_quote_conn_po_source'),
        ),
    ]
