# Generated by Django 5.2.6 on 2026-07-29 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0032_quotation_brand_column_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('pasted_text', 'Pasted Text'), ('excel', 'Excel'), ('pdf', 'PDF'), ('image', 'Image'), ('gmail', 'Gmail')], default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='GmailInquiryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('anchor_message_id', models.CharField(db_index=True, max_length=255)),
                ('selected_message_ids', models.JSONField(blank=True, default=list)),
                ('mode', models.CharField(choices=[('current_message', 'Current message'), ('selected_messages', 'Selected messages'), ('ai_thread', 'AI-assisted thread')], default='current_message', max_length=30)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('handoff_token_hash', models.CharField(blank=True, max_length=64)),
                ('handoff_expires_at', models.DateTimeField(blank=True, null=True)),
                ('handoff_used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('analyzing', 'Analyzing'), ('review_required', 'Review required'), ('ready', 'Ready'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('message_manifest', models.JSONField(blank=True, default=list)),
                ('attachment_manifest', models.JSONField(blank=True, default=list)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('candidates', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('analysis_attempts', models.PositiveIntegerField(default=0)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_gmail_inquiry_imports', to=settings.AUTH_USER_MODEL)),
                ('gmail_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_imports', to='quotations.gmailoauthconnection')),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_import', to='quotations.inquiry')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_import', to='quotations.quotation')),
                ('selected_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_gmail_inquiry_imports', to='quotations.company')),
                ('selected_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_gmail_inquiry_imports', to='quotations.companycontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GmailInquiryHandoffToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gmail_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_tokens', to='quotations.gmailinquiryimport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gmailinquiryimport',
            index=models.Index(fields=['mailbox_email', 'gmail_thread_id'], name='quotations__mailbox_080033_idx'),
        ),
        migrations.AddIndex(
            model_name='gmailinquiryimport',
            index=models.Index(fields=['status', 'created_at'], name='quotations__status_d02ce2_idx'),
        ),
        migrations.AddConstraint(
            model_name='gmailinquiryimport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_fingerprint', ''), _negated=True), fields=('source_fingerprint',), name='uniq_gmail_inquiry_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='gmailinquiryimport',
            constraint=models.UniqueConstraint(condition=models.Q(('handoff_token_hash', ''), _negated=True), fields=('handoff_token_hash',), name='uniq_gmail_inquiry_token_hash'),
        ),
        migrations.AddConstraint(
            model_name='gmailinquiryimport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), models.Q(('mailbox_email', ''), _negated=True), models.Q(('gmail_thread_id', ''), _negated=True)), fields=('mailbox_email', 'gmail_thread_id'), name='uniq_confirmed_gmail_inquiry_thread'),
        ),
        migrations.AddIndex(
            model_name='gmailinquiryhandofftoken',
            index=models.Index(fields=['gmail_import', 'expires_at'], name='quotations__gmail_i_073136_idx'),
        ),
    ]
