# Generated by Django 5.2.6 on 2026-07-31 15:59

import django.db.models.deletion
import django.utils.timezone
import quotations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0033_alter_inquiry_source_type_gmailinquiryimport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('finalized', 'Finalized'), ('revised', 'Revised'), ('pdf_downloaded', 'PDF Downloaded'), ('imported', 'Imported'), ('lpo_uploaded', 'LPO Uploaded'), ('proforma_downloaded', 'Proforma Downloaded'), ('outcome_updated', 'Outcome Updated'), ('followup_updated', 'Follow-up Updated'), ('email_prepared', 'Email Prepared'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed'), ('email_unknown', 'Email Delivery Unknown')], max_length=50),
        ),
        migrations.CreateModel(
            name='QuotationEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_mode', models.CharField(choices=[('gmail_reply', 'Reply in Gmail thread'), ('new_email', 'New Gmail email')], max_length=30)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unknown', 'Delivery unknown')], db_index=True, default='prepared', max_length=20)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('to_addresses', models.JSONField(blank=True, default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField()),
                ('trusted_source', models.JSONField(blank=True, default=dict)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source_gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('source_rfc_message_id', models.CharField(blank=True, max_length=998)),
                ('source_references', models.TextField(blank=True)),
                ('outbound_rfc_message_id', models.CharField(default=quotations.models.quotation_delivery_message_id, editable=False, max_length=255, unique=True)),
                ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_gmail_thread_id', models.CharField(blank=True, max_length=255)),
                ('attachment_filename', models.CharField(blank=True, max_length=255)),
                ('attachment_sha256', models.CharField(blank=True, max_length=64)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sending_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_deliveries', to=settings.AUTH_USER_MODEL)),
                ('gmail_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_deliveries', to='quotations.gmailoauthconnection')),
                ('gmail_inquiry_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_deliveries', to='quotations.gmailinquiryimport')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='email_delivery', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quotation', 'status'], name='quotations__quotati_8caff9_idx'), models.Index(fields=['gmail_thread_id', 'status'], name='quotations__gmail_t_01b4a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuotationEmailThreadSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('source_email', models.EmailField(max_length=254)),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('gmail_thread_id', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_thread_selections', to=settings.AUTH_USER_MODEL)),
                ('gmail_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_email_thread_selections', to='quotations.gmailoauthconnection')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_thread_selections', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quotation', 'expires_at'], name='quotations__quotati_57aa0a_idx')],
            },
        ),
    ]
