# Generated by Django 5.2.6 on 2026-08-01 02:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0034_alter_quotationauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationEmailOutboundSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_version', models.CharField(default='quotation_email_outbound_v1', editable=False, max_length=64)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('gmail_connection_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mailbox_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('delivery_mode', models.CharField(choices=[('gmail_reply', 'Reply in Gmail thread'), ('new_email', 'New Gmail email')], max_length=30)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField()),
                ('gmail_api_thread_id', models.CharField(blank=True, max_length=255)),
                ('source_gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('source_rfc_message_id', models.CharField(blank=True, max_length=998)),
                ('source_references', models.TextField(blank=True)),
                ('outbound_rfc_message_id', models.CharField(max_length=255)),
                ('attachment_filename', models.CharField(max_length=255)),
                ('attachment_sha256', models.CharField(max_length=64)),
                ('attachment_size', models.PositiveIntegerField()),
                ('raw_mime', models.BinaryField()),
                ('raw_mime_sha256', models.CharField(editable=False, max_length=64)),
                ('raw_mime_size', models.PositiveIntegerField(editable=False)),
                ('snapshot_sha256', models.CharField(db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_outbound_snapshots', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_snapshot', to='quotations.quotationemaildelivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationEmailDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='gmail', editable=False, max_length=30)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('gmail_connection_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mailbox_email', models.EmailField(max_length=254)),
                ('raw_mime_sha256', models.CharField(max_length=64)),
                ('expected_thread_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_delivery_attempts', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_attempts', to='quotations.quotationemaildelivery')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_attempts', to='quotations.quotationemailoutboundsnapshot')),
            ],
            options={
                'ordering': ['delivery_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='QuotationEmailDeliveryAttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('provider_sent', 'Provider confirmed sent'), ('provider_failed', 'Provider call failed'), ('provider_unknown', 'Provider result unknown'), ('reconciled_sent', 'Sent message verified by reconciliation')], max_length=30)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('provider_thread_id', models.CharField(blank=True, max_length=255)),
                ('provider_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_category', models.CharField(blank=True, max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_class', models.CharField(blank=True, max_length=255)),
                ('error_summary', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_email_delivery_attempt_events', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='quotations.quotationemaildeliveryattempt')),
            ],
            options={
                'ordering': ['attempt_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='quotations__event_t_355435_idx')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'event_key'), name='quotation_email_attempt_event_key_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='quotationemailoutboundsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('raw_mime_size__gt', 0)), name='quotation_email_snapshot_raw_size_positive'),
        ),
        migrations.AddIndex(
            model_name='quotationemaildeliveryattempt',
            index=models.Index(fields=['delivery', 'started_at'], name='quotations__deliver_c071d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotationemaildeliveryattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'sequence'), name='quotation_email_attempt_delivery_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='quotationemaildeliveryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='quotation_email_attempt_sequence_positive'),
        ),
    ]
