# Generated by Django 5.2.6 on 2026-09-05 17:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0043_quotation_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued / awaiting receipt'), ('delivered', 'Delivery confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('lpo_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_trn', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(blank=True)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('receipt_reference', models.CharField(blank=True, max_length=255)),
                ('receipt_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='quotations.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.deliverynote')),
                ('quotation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note_lines', to='quotations.quotationline')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['quotation', 'status'], name='quotations__quotati_b93593_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverynoteline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='delivery_note_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='deliverynoteline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__isnull', True), models.Q(('received_quantity__gte', 0), ('received_quantity__lte', models.F('quantity'))), _connector='OR'), name='delivery_note_received_within_sent'),
        ),
        migrations.AddConstraint(
            model_name='deliverynoteline',
            constraint=models.UniqueConstraint(fields=('delivery_note', 'quotation_line'), name='delivery_note_unique_quote_line'),
        ),
    ]
