# Generated by Django 5.2.6 on 2026-09-08 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_identity_notes_product_identity_review_state'),
        ('quotations', '0044_delivery_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='price_provenance',
            field=models.JSONField(blank=True, default=dict, db_default={}),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='price_review_required',
            field=models.BooleanField(default=False, db_default=False),
        ),
        migrations.CreateModel(
            name='QuotationPriceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('source_wording', models.TextField(blank=True)),
                ('previous', models.JSONField(default=dict)),
                ('entered_price', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotations.company')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_feedback', to='quotations.quotationline')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.product')),
                ('replacement_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_corrections', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecommendationRetirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('retired_before', models.DateTimeField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotations.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'product', 'unit', 'currency'), name='unique_price_retirement_context')],
            },
        ),
    ]
