# Generated by Django 5.2.6 on 2026-09-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_canonical_product'),
        ('quotations', '0045_quotationline_price_provenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProductIdentityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('same_product', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.company')),
                ('historical_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_identity_matches', to='api.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_identity_matches', to='api.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'product', 'historical_product'), name='unique_company_product_identity')],
            },
        ),
    ]
