# Generated by Django 5.2.6 on 2026-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0048_deliverynote_lpo_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='quotation_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
