# Generated by Django 5.2.6 on 2026-09-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0049_deliverynote_quotation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='continued_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='later_deliveries', to='quotations.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='deliver_later',
            field=models.BooleanField(default=False),
        ),
    ]
