# Generated by Django 5.2.6 on 2026-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0050_delivery_later_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='show_expiry_column',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='expiry',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
