# Generated by Django 5.2.6 on 2026-09-22 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0051_delivery_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=12)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('supply_date', models.DateField(default=django.utils.timezone.localdate)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_trn', models.CharField(blank=True, max_length=15)),
                ('attention', models.CharField(blank=True, max_length=255)),
                ('quotation_reference', models.CharField(blank=True, max_length=120)),
                ('lpo_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('supplier_snapshot', models.JSONField(blank=True, default=dict)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('issued_pdf', models.BinaryField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='quotations.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_invoices', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tax_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='quotations.taxinvoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
