# Generated by Django 5.2.6 on 2026-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0055_quotation_expiry_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryline',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
