# Generated by Django 5.2.6 on 2026-05-26 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('credit', 'Credit'), ('insurance', 'Insurance'), ('clinic', 'Clinic'), ('branch', 'Branch'), ('card', 'Card'), ('misc', 'Misc'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_ignored', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_accounting_module', 'Can view Accounting module'), ('upload_accounting_statement', 'Can upload accounting statements'), ('generate_accounting_statement', 'Can generate accounting statements'), ('edit_accounting_customer', 'Can edit accounting customers'), ('download_accounting_statement', 'Can download accounting statements')],
                'indexes': [models.Index(fields=['customer_code', 'normalized_name'], name='accounting__custome_54cd44_idx'), models.Index(fields=['category', 'is_ignored'], name='accounting__categor_fc9ddd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountingImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('source_size', models.PositiveIntegerField(default=0)),
                ('category_filename', models.CharField(blank=True, max_length=255)),
                ('category_sha256', models.CharField(blank=True, max_length=64)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('reviewed', 'Reviewed'), ('generated', 'Generated'), ('archived', 'Archived')], db_index=True, default='parsed', max_length=30)),
                ('parsed_row_count', models.PositiveIntegerField(default=0)),
                ('skipped_row_count', models.PositiveIntegerField(default=0)),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('due_customer_count', models.PositiveIntegerField(default=0)),
                ('generated_statement_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('parse_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingImportCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('credit', 'Credit'), ('insurance', 'Insurance'), ('clinic', 'Clinic'), ('branch', 'Branch'), ('card', 'Card'), ('misc', 'Misc'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_0_30', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_30_60', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_60_90', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_over_90', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_days', models.IntegerField(default=0)),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('is_due', models.BooleanField(db_index=True, default=False)),
                ('is_ignored', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('due', 'Due'), ('not_due', 'Not Due'), ('ignored', 'Ignored'), ('needs_review', 'Needs Review')], db_index=True, default='not_due', max_length=30)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounting.accountingimport')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_summaries', to='accounting.accountcustomer')),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingInvoiceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField()),
                ('customer_code', models.CharField(blank=True, max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('bill_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('invoice_date', models.DateField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_0_30', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_30_60', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_60_90', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bucket_over_90', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('days', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_rows', to='accounting.accountingimportcustomer')),
            ],
            options={
                'ordering': ['invoice_date', 'bill_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingimport',
            index=models.Index(fields=['source_sha256', 'report_date'], name='accounting__source__e6d6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingimport',
            index=models.Index(fields=['status', 'created_at'], name='accounting__status_4d452c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingimportcustomer',
            index=models.Index(fields=['accounting_import', 'status'], name='accounting__account_0a2a32_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingimportcustomer',
            index=models.Index(fields=['accounting_import', 'is_due', 'is_ignored'], name='accounting__account_5b0e84_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingimportcustomer',
            index=models.Index(fields=['category', 'email'], name='accounting__categor_e9588d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingimportcustomer',
            unique_together={('accounting_import', 'customer')},
        ),
        migrations.AddIndex(
            model_name='accountinginvoicerow',
            index=models.Index(fields=['import_customer', 'invoice_date'], name='accounting__import__bade4b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountinginvoicerow',
            index=models.Index(fields=['days'], name='accounting__days_7b3b3c_idx'),
        ),
    ]
