# Generated by Django 5.2.6 on 2026-05-26 05:07

import re

from django.db import migrations, models


def split_bill_reference(value):
    text = str(value or "").strip()
    if not text:
        return "", ""
    match = re.match(r"^(\d{6})(?:-(.*))?$", text)
    if not match:
        return text, ""
    invoice_number = match.group(1)
    reference = (match.group(2) or "").strip()
    if not reference or set(reference) <= {"-"}:
        return invoice_number, ""
    return invoice_number, reference


def populate_invoice_and_lpo_fields(apps, schema_editor):
    AccountingInvoiceRow = apps.get_model("accounting", "AccountingInvoiceRow")
    rows_to_update = []
    for row in AccountingInvoiceRow.objects.all().only("id", "bill_number", "invoice_number", "lpo_reference").iterator():
        invoice_number, lpo_reference = split_bill_reference(row.bill_number)
        if row.invoice_number != invoice_number or row.lpo_reference != lpo_reference:
            row.invoice_number = invoice_number
            row.lpo_reference = lpo_reference
            rows_to_update.append(row)
        if len(rows_to_update) >= 1000:
            AccountingInvoiceRow.objects.bulk_update(rows_to_update, ["invoice_number", "lpo_reference"])
            rows_to_update = []
    if rows_to_update:
        AccountingInvoiceRow.objects.bulk_update(rows_to_update, ["invoice_number", "lpo_reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinginvoicerow',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='accountinginvoicerow',
            name='lpo_reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.RunPython(populate_invoice_and_lpo_fields, migrations.RunPython.noop),
    ]
