"""
Django settings for pharmacy_api project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import re
from urllib.parse import urlparse
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import cloudinary

# ---- load env file ----
load_dotenv()  # reads .env at project root

BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name):
    return [item.strip().lower() for item in os.environ.get(name, "").split(",") if item.strip()]


def database_host(database_url):
    if not database_url:
        return ""
    parsed = urlparse(database_url)
    return (parsed.hostname or "").lower()


# ---- security & debug from env ----
DEBUG = env_bool("DEBUG", False)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DEBUG=False.")
ALLOWED_HOSTS = [host.strip() for host in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]
DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///db.sqlite3")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Safety guard: local DEBUG mode must not accidentally write to production Neon.
# If you intentionally use a separate Neon development branch locally, set
# ALLOW_DEBUG_NEON_DATABASE=1 in your local environment after confirming it is
# not the production database.
DATABASE_HOST = database_host(DATABASE_URL)
PRODUCTION_DATABASE_HOSTS = env_list("PRODUCTION_DATABASE_HOSTS")
ALLOW_DEBUG_NEON_DATABASE = env_bool("ALLOW_DEBUG_NEON_DATABASE", False)
if DEBUG and DATABASE_HOST:
    is_configured_production_host = DATABASE_HOST in PRODUCTION_DATABASE_HOSTS
    is_neon_host = DATABASE_HOST.endswith(".neon.tech")
    if is_configured_production_host or (is_neon_host and not ALLOW_DEBUG_NEON_DATABASE):
        raise ImproperlyConfigured(
            "Refusing to start with DEBUG=True while DATABASE_URL points to a Neon database host. "
            "Local development should use SQLite, local PostgreSQL, or a separate Neon dev branch. "
            "If this is intentionally a non-production Neon dev database, set ALLOW_DEBUG_NEON_DATABASE=1. "
            "Do not point local backend/.env at production Neon."
        )

# ---- installed apps ----
INSTALLED_APPS = [
    'django.contrib.admin','django.contrib.auth','django.contrib.contenttypes',
    'django.contrib.sessions','django.contrib.messages','django.contrib.staticfiles',
    'rest_framework','corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'cloudinary_storage',  # Must be before django.contrib.staticfiles
    'cloudinary',
    'api',
    'quotations',
    'accounting',
]

# ---- middleware (CORS FIRST) ----
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
# For development, allow localhost. For production, set CORS_ALLOWED_ORIGINS in .env
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000'  # Development default
).split(',')

CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'pharmacy_api.urls'

# ---- templates ----
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pharmacy_api.wsgi.application'

# ---- database configuration ----
# PostgreSQL via Neon (cloud database)
# Good for: production, learning real-world setup
DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600
    )
}

# For local development with SQLite (simpler but less realistic):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# ---- timezone ----
TIME_ZONE = "Asia/Dubai"
USE_TZ = True

# ---- static files (production ready with Whitenoise) ----
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Where collectstatic puts files

# ---- quotation PDF branding ----
# Override these in Railway/local env when the final business details are confirmed.
QUOTATION_COMPANY_NAME = os.environ.get("QUOTATION_COMPANY_NAME", "Al Ameen Pharmacy")
QUOTATION_COMPANY_NAME_AR = os.environ.get("QUOTATION_COMPANY_NAME_AR", "")
QUOTATION_COMPANY_ADDRESS = os.environ.get("QUOTATION_COMPANY_ADDRESS", "Dubai, United Arab Emirates")
QUOTATION_COMPANY_PHONE = os.environ.get("QUOTATION_COMPANY_PHONE", "+971 50 545 6388")
QUOTATION_COMPANY_EMAIL = os.environ.get("QUOTATION_COMPANY_EMAIL", "alameenpharmacyllc@gmail.com")
QUOTATION_COMPANY_TRN = os.environ.get("QUOTATION_COMPANY_TRN", "")
QUOTATION_LOGO_PATH = os.environ.get(
    "QUOTATION_LOGO_PATH",
    str(BASE_DIR.parent / "frontend" / "public" / "brand" / "al-ameen-pharmacy-logo-dark.png"),
)
QUOTATION_DEFAULT_TERMS = os.environ.get(
    "QUOTATION_DEFAULT_TERMS",
    "Prices are subject to stock availability and final confirmation. This quotation is confidential and intended for the named customer only.",
)
QUOTATION_VALIDITY_DAYS = int(os.environ.get("QUOTATION_VALIDITY_DAYS", "30"))
QUOTATION_PAYMENT_TERMS = os.environ.get("QUOTATION_PAYMENT_TERMS", "As per mutually agreed terms.")
QUOTATION_IMPORT_MAX_UPLOAD_BYTES = int(os.environ.get("QUOTATION_IMPORT_MAX_UPLOAD_BYTES", str(5 * 1024 * 1024)))
QUOTATION_IMPORT_MAX_EXCEL_ROWS = int(os.environ.get("QUOTATION_IMPORT_MAX_EXCEL_ROWS", "500"))
QUOTATION_IMPORT_MAX_EXCEL_SHEETS = int(os.environ.get("QUOTATION_IMPORT_MAX_EXCEL_SHEETS", "10"))
QUOTATION_IMPORT_MAX_PDF_PAGES = int(os.environ.get("QUOTATION_IMPORT_MAX_PDF_PAGES", "10"))
QUOTATION_IMPORT_STORE_SOURCE_FILES = bool(int(os.environ.get("QUOTATION_IMPORT_STORE_SOURCE_FILES", "1")))
QUOTATION_PRIVATE_STORAGE_ROOT = os.environ.get("QUOTATION_PRIVATE_STORAGE_ROOT", str(BASE_DIR / "private_media" / "quotations"))
QUOTATION_IMPORT_OCR_PROVIDER = os.environ.get("QUOTATION_IMPORT_OCR_PROVIDER", "")
QUOTATION_LOGO_MAX_UPLOAD_BYTES = int(os.environ.get("QUOTATION_LOGO_MAX_UPLOAD_BYTES", str(2 * 1024 * 1024)))
QUOTATION_BRANDING_IMAGE_MAX_UPLOAD_BYTES = int(os.environ.get("QUOTATION_BRANDING_IMAGE_MAX_UPLOAD_BYTES", str(2 * 1024 * 1024)))
QUOTATION_PDF_ALLOW_REMOTE_IMAGES = env_bool("QUOTATION_PDF_ALLOW_REMOTE_IMAGES", False)
QUOTATION_PDF_REMOTE_IMAGE_TIMEOUT_SECONDS = float(os.environ.get("QUOTATION_PDF_REMOTE_IMAGE_TIMEOUT_SECONDS", "2.0"))
QUOTATION_PDF_ALLOWED_REMOTE_IMAGE_HOSTS = [
    host.strip().lower()
    for host in os.environ.get("QUOTATION_PDF_ALLOWED_REMOTE_IMAGE_HOSTS", "res.cloudinary.com").split(",")
    if host.strip()
]

# ---- quotation AI-assisted parsing ----
# API keys stay in environment variables. Daily enable/disable controls live in
# Quotation Settings so staff can decide when AI cleanup is allowed.
QUOTATION_AI_PARSE_GLOBAL_ENABLED = env_bool("QUOTATION_AI_PARSE_GLOBAL_ENABLED", True)
QUOTATION_AI_PARSE_PROVIDER = os.environ.get("QUOTATION_AI_PARSE_PROVIDER", "openai").strip().lower()
QUOTATION_AI_PARSE_TEXT_MODEL = os.environ.get("QUOTATION_AI_PARSE_TEXT_MODEL", "gpt-4.1-mini")
QUOTATION_AI_PARSE_VISION_MODEL = os.environ.get("QUOTATION_AI_PARSE_VISION_MODEL", "gpt-4.1-mini")
QUOTATION_AI_PARSE_MAX_TEXT_CHARS = int(os.environ.get("QUOTATION_AI_PARSE_MAX_TEXT_CHARS", "20000"))
QUOTATION_AI_PARSE_MAX_PDF_PAGES = int(os.environ.get("QUOTATION_AI_PARSE_MAX_PDF_PAGES", "10"))
QUOTATION_AI_PARSE_MAX_RENDERED_PAGES = int(os.environ.get("QUOTATION_AI_PARSE_MAX_RENDERED_PAGES", "3"))
QUOTATION_AI_PARSE_IMAGE_MAX_DIMENSION = int(os.environ.get("QUOTATION_AI_PARSE_IMAGE_MAX_DIMENSION", "1400"))
QUOTATION_AI_PARSE_IMAGE_SCALE = float(os.environ.get("QUOTATION_AI_PARSE_IMAGE_SCALE", "1.4"))
QUOTATION_AI_PARSE_TIMEOUT_SECONDS = int(os.environ.get("QUOTATION_AI_PARSE_TIMEOUT_SECONDS", "60"))

# ---- accounting overdue statement imports ----
ACCOUNTING_IMPORT_MAX_UPLOAD_BYTES = int(os.environ.get("ACCOUNTING_IMPORT_MAX_UPLOAD_BYTES", str(25 * 1024 * 1024)))
ACCOUNTING_STATEMENT_ZIP_SYNC_LIMIT = int(os.environ.get("ACCOUNTING_STATEMENT_ZIP_SYNC_LIMIT", "75"))

# ---- Cloudinary Configuration (Cloud Image Storage) ----
# Images will be stored on Cloudinary CDN instead of local filesystem

# Parse and configure Cloudinary from CLOUDINARY_URL environment variable
cloudinary_url = os.environ.get('CLOUDINARY_URL', '')
if cloudinary_url:
    # Extract credentials from CLOUDINARY_URL format: cloudinary://api_key:api_secret@cloud_name
    match = re.match(r'cloudinary://(\d+):([^@]+)@(.+)', cloudinary_url)
    if match:
        api_key, api_secret, cloud_name = match.groups()
        cloudinary.config(
            cloud_name=cloud_name,
            api_key=api_key,
            api_secret=api_secret,
            secure=True
        )

CLOUDINARY_STORAGE = {
    'CLOUDINARY_URL': cloudinary_url,
}

# Media files URL
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django 5.x STORAGES configuration
# Configure both static files and media files storage
if cloudinary_url:
    # Production: Use Cloudinary for media files, Whitenoise for static files
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Development: Use local filesystem for both
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# ---- Stripe Configuration ----
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')

# ---- Email Configuration ----
# For development: File backend (saves emails to files, avoids Unicode issues)
# For production: Use SMTP backend with real email service

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.filebased.EmailBackend'  # Development default
)

# File-based email settings (for development)
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'  # Emails will be saved here

# SMTP Configuration (for production)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = bool(int(os.environ.get('EMAIL_USE_TLS', '1')))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@alameenpharmacy.com')
ORDER_NOTIFICATION_EMAILS = [
    email.strip()
    for email in os.environ.get('ORDER_NOTIFICATION_EMAILS', '').split(',')
    if email.strip()
]

# To use Gmail SMTP in production, add to .env:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=1
# EMAIL_HOST_USER=your-email@gmail.com
# EMAIL_HOST_PASSWORD=your-app-password
# DEFAULT_FROM_EMAIL=AL AMEEN PHARMACY <noreply@alameenpharmacy.com>


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---- security settings (HTTPS enforcement for production) ----
# These settings are only active when DEBUG=False (production)
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Force HTTPS
    SECURE_HSTS_SECONDS = 31536000  # Remember HTTPS for 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply to all subdomains
    SECURE_HSTS_PRELOAD = True  # Allow browser preload list
    SESSION_COOKIE_SECURE = True  # Only send session cookies over HTTPS
    CSRF_COOKIE_SECURE = True  # Only send CSRF cookies over HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # For reverse proxy

    # CSRF trusted origins for Railway deployment
    CSRF_TRUSTED_ORIGINS = [
        'https://*.up.railway.app',
        'https://*.railway.app',
    ]

# ---- rest framework ----
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # read Bearer tokens
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",  # start open; we’ll lock views we need
    ),
}
REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"] = (
    "rest_framework.permissions.IsAuthenticated",
)
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
    "registration": os.environ.get("REGISTRATION_THROTTLE_RATE", "20/hour"),
    "login": os.environ.get("LOGIN_THROTTLE_RATE", "10/minute"),
    "token_refresh": os.environ.get("TOKEN_REFRESH_THROTTLE_RATE", "30/minute"),
    "password_reset": os.environ.get("PASSWORD_RESET_THROTTLE_RATE", "5/hour"),
    "password_reset_confirm": os.environ.get("PASSWORD_RESET_CONFIRM_THROTTLE_RATE", "20/hour"),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.environ.get("JWT_ACCESS_TOKEN_MINUTES", "30"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.environ.get("JWT_REFRESH_TOKEN_DAYS", "14"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}
